### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [mergesort/Anchorman#2]
Hey @mergesort, your library is really interesting.

The only problem I found was the `README.md`, which lacks a little bit of information
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib.

What are your thoughts?

**Comment by mergesort** [comment]
Hey @lfarah! Thanks for the compliment. The readme currently covers the entire API layer, and the rest is relatively tongue in cheek. Do you have any suggestions for how you'd like to see it improved, other than just making it into a template?

Suggestions welcome!

**Comment by lfarah** [comment]
Definitely!
I'd be cool if you had the following sections:

### Installation

### Meta

### Requirements

**Comment by lfarah** [comment]
And please leave the Gifs.... I loved them!

**Comment by mergesort** [comment]
Good feedback, will take care of that! What do you consider to be meta, and requirements?

**Comment by lfarah** [comment]
So Meta would be the part where you talk about yourself, your twitter and the library's license
![screen shot 2016-06-02 at 2 24 14 pm](https://cloud.githubusercontent.com/assets/6511079/15761557/ba43c7de-28cd-11e6-93c5-1627dbb4e25a.png)

Requirements is where you say the minimum xcode and iOS version u need to run the library
![screen shot 2016-06-02 at 2 25 05 pm](https://cloud.githubusercontent.com/assets/6511079/15761573/d2cc1658-28cd-11e6-9b76-fe95c0e7ae83.png)

**Comment by mergesort** [comment]
Sounds good! I'll take this feedback and incorporate it into the README later tonight. 😄

**Comment by lfarah** [comment]
## Installation

#### CocoaPods

You can use [CocoaPods](http://cocoapods.org/) to install `Anchorman` by adding it to your `Podfile`:

``` ruby
platform :ios, '8.0'
use_frameworks!
pod 'Anchorman'
```

To get the full benefits import `Anchorman` wherever you import UIKit

``` swift
import UIKit
import Anchorman
```

#### Manually
1. Download and drop `Anchorman.swift` in your project.  
2. Congratulations!

**Comment by mergesort** [comment]
@lfarah It's [updated](https://github.com/mergesort/Anchorman/blob/master/README.md). Feel free to leave me some more feedback if there's anything you'd like to see, or feel free to file a PR.

**Comment by lfarah** [comment]
hahahahha the Readme is awesome. Congrats!
